---

- name: Manage distro common packages to a state of {{ pkg_state }}
  package:
    name: "{{ pkg }}"
    state: "{{ pkg_state }}"
  when:
    - pkg is defined


- include: "{{ linux_distro[ansible_distribution] }}.yml"
