---
- name: Reboot Node
  shell: nohup bash -c "sleep 2s && shutdown -r now" &
  notify: wait
  listen: reboot

- name: Wait for Node to come up
  wait_for_connection:
    timeout: 240
    delay: 20
  listen: wait
